name: applewin # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: "1.30.18.10" # just for humans, typically '1.2+git' or '1.3.2'
summary: AppleWin Apple II emulator # 79 char long summary
description: |
  Apple II emulator for Linux

# grade: devel # must be 'stable' to release into candidate/stable channels
# confinement: devmode # use 'strict' once you have the right plugs and slots

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  applewin-part:
    plugin: cmake
    source: .
    source-type: local
    # source-branch: snapcraft
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SA2=ON
    build-packages:
      - cmake
      - g++
      - ninja-build
      - pkg-config
      - libyaml-dev
      - libminizip-dev
      - libboost-program-options-dev
      - libsdl2-image-dev
      - libsdl2-dev
      - libgles-dev
      - libpcap-dev
      - libslirp-dev
      # - qtbase5-dev
      # - qtmultimedia5-dev
      # - libqt5gamepad5-dev
      # - libqt5multimedia5-plugins
      # - libncurses-dev
      # - libevdev-dev
    stage-packages:
      - libyaml-0-2
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libboost-program-options1.74.0
      - libminizip1
      - libpcap0.8
      - libslirp0
      - libgles2

plugs:
  etc-xattr:
    interface: system-files
    read:
      - /etc/xattr.conf

apps:
  applewin:
    command: usr/bin/sa2
    extensions:
      - gnome
    plugs:
      - network
      - network-bind
      - audio-playback
      - joystick
      - home
      - removable-media
      # - hardware-observe  # what is this for? it complains about /run/udev/data/c241:5
      - screen-inhibit-control
      - etc-xattr
