name: xa2e
base: core22
version: "1.30.18.10"
title: eXtended Apple ][ Emulator
issues: https://github.com/audetto/AppleWin/issues
website: https://github.com/audetto/AppleWin
summary: Apple ][ emulator for Linux
icon: snap/gui/xa2e.svg
description: |
  Linux version of AppleWin emulator.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  xa2e-part:
    plugin: cmake
    source: .
    source-type: local
    # source-branch: snapcraft
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SA2=ON
    build-packages:
      - cmake
      - g++
      - ninja-build
      - pkg-config
      - libyaml-dev
      - libminizip-dev
      - libboost-program-options-dev
      - libsdl2-image-dev
      - libsdl2-dev
      - libgles-dev
      - libpcap-dev
      - libslirp-dev
      # - qtbase5-dev
      # - qtmultimedia5-dev
      # - libqt5gamepad5-dev
      # - libqt5multimedia5-plugins
      # - libncurses-dev
      # - libevdev-dev
    stage-packages:
      - libyaml-0-2
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libboost-program-options1.74.0
      - libminizip1
      - libslirp0
      - libgles2

apps:
  xa2e:
    command: usr/bin/sa2
    extensions:
      - gnome
    plugs:
      - network
      - network-bind
      - audio-playback
      - joystick
      - home
      - removable-media
      - screen-inhibit-control
      # - hardware-observe  # it complains about /run/udev/data/c241:5, something network / pcap related???
      # - etc-xattr  # complains about /etc/xattr.conf, is it important?
